param([string]$BackendZip='C:/Deploy/kittyhp-backend-offline.zip',[string]$FrontendZip='C:/Deploy/kittyhp-frontend-offline.zip',[string]$BackendDir='C:/Services/kittyhp-backend',[string]$FrontendDir='C:/inetpub/kittyhp-frontend',[string]$NssmPath='C:/Tools/nssm/nssm.exe',[string]$NodePath='C:/Program Files/nodejs/node.exe',[string]$ServiceName='KittyHP-Backend',[string]$IISAppPoolName='KittyHP',[string]$IISSiteName='Default Web Site',[string]$BackupBase='C:/Backups',[string]$DeployRoot='C:/Deploy',[string]$EnvFile='', [int]$BackendPort=3009, [int]$FrontendPort=8010, [switch]$InstallServiceIfMissing, [switch]$SkipBackend, [switch]$SkipFrontend)
$ErrorActionPreference='Stop'; Set-StrictMode -Version Latest
function Mirror($s,$d){New-Item -ItemType Directory -Force -Path $d|Out-Null;& robocopy $s $d /MIR /COPY:DAT /R:3 /W:2 /NFL /NDL /NJH /NJS /NP|Out-Null;if($LASTEXITCODE -gt 7){throw "Robocopy fallo ($LASTEXITCODE)."}}
function Set-Port($path,$port){if(!(Test-Path $path)){throw "No existe .env: $path"};$lines=Get-Content $path; if($lines -match '^\s*PORT\s*='){ $lines=$lines -replace '^\s*PORT\s*=.*$',"PORT=$port" } else { $lines += "PORT=$port" }; Set-Content -LiteralPath $path -Value $lines -Encoding UTF8}
if($SkipBackend -and $SkipFrontend){throw 'No puedes omitir ambos componentes.'}; if(!$SkipBackend -and !(Test-Path $BackendZip)){throw "No existe $BackendZip"}; if(!$SkipFrontend -and !(Test-Path $FrontendZip)){throw "No existe $FrontendZip"}
$stamp=Get-Date -Format yyyyMMdd-HHmmss; $backup=Join-Path $BackupBase "kittyhp-$stamp"; $tmp=Join-Path $DeployRoot "_kittyhp-$stamp"; New-Item -ItemType Directory -Force -Path $backup,$tmp|Out-Null
try { if(!$SkipBackend){$stage=Join-Path $tmp 'backend';Expand-Archive $BackendZip $stage -Force;if(Test-Path $BackendDir){Mirror $BackendDir (Join-Path $backup 'backend')};$currentEnv=Join-Path $BackendDir '.env';if(Test-Path $currentEnv){Copy-Item $currentEnv (Join-Path $stage '.env') -Force}elseif($EnvFile){Copy-Item $EnvFile (Join-Path $stage '.env') -Force};Set-Port (Join-Path $stage '.env') $BackendPort;foreach($persistent in @('uploads','logs')){$source=Join-Path $BackendDir $persistent;if(Test-Path $source){Mirror $source (Join-Path $stage $persistent)}};New-Item -ItemType Directory -Force -Path $BackendDir|Out-Null;Mirror $stage $BackendDir;if(Get-Service $ServiceName -ErrorAction SilentlyContinue){Stop-Service $ServiceName -Force;Start-Service $ServiceName}elseif($InstallServiceIfMissing){& $NssmPath install $ServiceName $NodePath (Join-Path $BackendDir 'dist/main.js');Start-Service $ServiceName}}
  if(!$SkipFrontend){$stage=Join-Path $tmp 'frontend';Expand-Archive $FrontendZip $stage -Force;if(Test-Path $FrontendDir){Mirror $FrontendDir (Join-Path $backup 'frontend')};New-Item -ItemType Directory -Force -Path $FrontendDir|Out-Null;Mirror $stage $FrontendDir;try{Import-Module WebAdministration -ErrorAction Stop;if(!(Get-WebBinding -Name $IISSiteName -Protocol http -Port $FrontendPort -ErrorAction SilentlyContinue)){New-WebBinding -Name $IISSiteName -Protocol http -Port $FrontendPort -IPAddress '*' -HostHeader '' | Out-Null};Restart-WebAppPool $IISAppPoolName}catch{Write-Warning $_.Exception.Message}}
  Write-Host "KittyHP actualizado. Backup: $backup" -ForegroundColor Green
} finally {if(Test-Path $tmp){Remove-Item -Recurse -Force $tmp -ErrorAction SilentlyContinue}}
